config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :posts
  resources :reviews
  resources :registrations, only: [:create]
  root 'home#index'
  resources :tours do
    member do
      put 'like', to:'tours#upvote'
      put 'unlike', to:'tours#downvote'
    end
  end
  devise_for :users
  resources :joinedtours
  resources :wishlists
  resources :relationships, only: [:create, :destroy]
  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'logout', to: 'devise/sessions#destroy'
  get 'create', to: 'devise/registrations#new'
  resources :users, only: [:index, :show, :edit, :update, :change_name] do
    member do
      get 'following', to: 'users#following'
      get 'followers', to: 'users#followers'

    end
  end
end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/joinedtour.rb
class Joinedtour < ApplicationRecord
	belongs_to :tour
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many_attached :images
  validates :content, presence: true
  validates :user_id, presence: true

end

app/models/registration.rb
class Registration < ApplicationRecord
	belongs_to :user

	def process_payments
		customer = Stripe::Customer.create(email: email, card: card_token)
		Stripe::Charge.create(customer: customer.id,
			                   amount: 10000*100,
			                   description: 'One Time Payment',
			                   currency: 'usd')
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name:"User", foreign_key:"follower_id"
	belongs_to :followed, class_name:"User", foreign_key:"followed_id"
end

app/models/response.rb
class Response < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :tour
	belongs_to :user
end

app/models/tour.rb
class Tour < ApplicationRecord
	belongs_to :host, class_name:"User", foreign_key:"host_id"
	has_many :reviews
	has_many_attached :images
	has_many :joinedtours
	has_many :wishlists
	has_many :interested_users, :through => :joinedtours, :source => :user
	has_many :wishlisted_by_users, :through => :wishlists, :source => :user
	acts_as_votable

	validates :title, presence: true, length: {maximum: 70}
	validates :description, presence: true, length: {maximum: 500}
	validates :budget, presence: true
	validates :reg_date_ends, presence: true
	validates :places, presence: true
	validates :services, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         acts_as_voter 
         
         has_many :hosted_tours, class_name:"Tour", foreign_key:"host_id"
         has_many :reviews
         has_many :blogs
         has_many :posts
         has_many :comments
         has_many :joinedtours
         has_many :wishlists
         has_many :interested_tours, :through => :joinedtours, :source => :tour
         has_many :wishlisted_tours, :through => :wishlists, :source => :tour
         has_one_attached :profile
         has_one :registration

         ## relationship section

         has_many :active_relationships, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
         has_many :passive_relationships, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy

         has_many :followers, through: :passive_relationships, source: :follower
         has_many :following, through: :active_relationships, source: :followed

         ###
         before_save :email_down
         VALID_REGEX_VALUE = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :first_name, presence: true, length: { maximum: 50 }
    validates :profile, presence: true
    validates :last_name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
         format: { with: VALID_REGEX_VALUE }, uniqueness: { case_sensitive: false }

         ### tour section
         def join tour
         	interested_tours << tour
         	if wishlisted?(tour)
         		remove_from_wishlist(tour)
         	end
         end
         def feed
            following_ids_subselect = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
            Post.where(" user_id IN (#{following_ids_subselect}) OR user_id = :user_id", user_id: id)
        end

         def joined?(tour)
         	interested_tours.include?(tour)
         end


         #### wishlist section
         def add_to_wishlist tour
         	wishlisted_tours << tour
         end

         def wishlisted?(tour)
         	wishlisted_tours.include?(tour)
         end

         def remove_from_wishlist(tour)
         	wishlisted_tours.delete(tour)
         end

         #### relationship section

         def follow(user)
             following << user
         end

         def unfollow(user)
             following.delete(user)
         end

         def followed?(user)
             following.include?(user)
         end

private

def email_down
    self.email = email.downcase
end



end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :tour
	belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only:[:show, :edit, :following, :followers]

	def index
		@users = User.order(created_at: :desc).paginate(page: params[:page], per_page: 25)
	end

	def show
		@posts = @user.posts.paginate(page: params[:page], per_page: 4)
	end

	def edit
		
	end

	def update
		
	end
	def following
		@following = @user.following
	end

	def followers
		@followers = @user.followers
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/joinedtours_helper.rb
module JoinedtoursHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/users/change_name.html.erb
<h2>Change Profile</h2>
<%= form_for @user do |form| %>
	<div class="field">
		<%= form.label :first_name %>
		<%= form.text_field :first_name %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h4 class="center-align">Update Info</h4>
<div class="container">
  <div class="row">
    <div class="col s12 center-align">
<%= form_for @user do |f| %>
<div class="row">
  <div class="input-field col m6">
    <i class="material-icons prefix">account_circle</i>
    <%= f.text_field :first_name, autofocus: true %>
    <%= f.label "first Name" %><br />
  </div>

  <div class="input-field col m6">
    <i class="material-icons prefix">assignment_ind</i>
    <%= f.text_field :last_name %>
    <%= f.label "Last Name" %><br />
  </div>
  </div>


  <div class="row">
  <div class="input-field col m6">
    <i class="material-icons prefix">contact_mail</i>
    <%= f.text_field :email %>
    <%= f.label "Email" %><br />
  </div>

   <div class="input-field col m6">
    <i class="material-icons prefix">phone</i>
    <%= f.phone_field :phone %>
    <%= f.label "Contact No" %><br />
  </div>
</div>

  <div class="row" >
    <div class="input-field col m4">
    <i class="material-icons prefix">cake</i>
    <%= f.text_field :dob_month %>
    <%= f.label "Birth Month" %><br />
  </div>

  <div class="input-field col m4">
    <i class="material-icons prefix">cake</i>
    <%= f.text_field :dob_day %>
    <%= f.label "Birth Day" %><br />
  </div>

  <div class="input-field col m4">
    <i class="material-icons prefix">cake</i>
    <%= f.text_field :dob_year %>
    <%= f.label "Birth Year" %><br />
  </div>
  </div>

 <div class="row">
  <div class="input-field col m6 ">
    <i class="material-icons prefix">screen_lock_landscape</i>
    <%= f.password_field :password, autocomplete: "new-password" %>
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
  </div>

  <div class="input-field col m6 ">
    <i class="material-icons prefix">lock_outline</i>
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    <%= f.label :"Confirm Password" %><br />
  </div>
  </div>

   <div class="row">
  <div class="input-field col m4 col s8 offset-s1 offset-m5">
   <div class="file-field input-field">
    <div class="btn ">
    <%= f.label :profile, class:"black-text" %>
    <%= f.file_field :profile%>
  </div>
  
  </div>
  </div>
  </div>


<div class="row">
  <div class="col m12">
    
  <div class="actions waves-effect waves-light btn">
    <%= f.submit "Update" %>
  </div>  
<% end %>

</div>
</div>
</div>
</div>
</div>

app/views/users/index.html.erb
<h3>All users</h3>
<% @users.in_groups_of(4, false).each do |group| %>
<div class="row">
  <% group.each do |user| %>
  <%= link_to user_path(user) do %>
	<div class="col m3 s12">
  <div class="cardo">
	<% if user.profile.attachment.present? %>
  <%= image_tag user.profile, alt:"Avatar", style:"width:100%;height:300px" %>
  <% else %>
	<%= image_tag "img_avatar.png", alt:"Avatar", style:"width:100%; height:300px" %>
  <% end %>
  <div class="containero">
    <h5 class="center-align"><%= user.first_name %> <%= user.last_name %></h5> 
    <span>Followers <%= user.followers.count %></span> 
    <span class="right">Following <%= user.following.count %></span> 
    
    <div class="followbtn">
      <b>Follow</b>
    </div>
  </div>
</div>
</div>
<% end %>
<% end %>
</div>
<% end %>
<div class="center"><%= will_paginate @users %></div>

app/views/users/show.html.erb
<div class="row user-info">
	<div class="col m6 offset-m1 s12">
		<div class="row">
		<div class="col m1" style="margin-top: 10px;">
		<% if @user.profile.attachment.present? %>
		<%= image_tag @user.profile, style:"width:70px;height:70px;border-radius:50%"  %>
		<% else %>
		<%= image_tag "img_avatar.png", style:"width:70px;height:70px;border-radius:50%;float:left"  %>
		<% end %>
		</div>
		<div class="col m5 s12">
		<h5 style="margin-left: 40px;"><%= @user.first_name %> <%= @user.last_name %></h5>
		<p style="margin-left: 40px;margin-top: -10px">@<%= @user.first_name.downcase %></p>
		</div>
		</div>
		<div class="row">
			<div class="col m3">
				<p><%= link_to followers_user_path(@user) do %>Followers <%= @user.followers.count %><% end %></p>
			</div>
			<div class="col m3">
				<p class="right"><%= link_to following_user_path(@user) do %>Following <%= @user.following.count %><% end %></p>
			</div> 
		</div>
		<div class="row ">
			<div class="col m6 folow">
				<% if current_user.followed? @user %>
				<p><%= link_to 'UnFollow', relationship_path(@user,user_id: @user.id), method: :delete %></p>
				<% else %>
				<p><%= link_to 'Follow', relationships_path(user_id: @user.id), method: :post %></p>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col m5">
		<h3>Posts</h3>
		<% @posts.each do |post| %>
		<p class="user-post"><%= truncate(post.content) %></p>
		<% end %>
		<%= will_paginate @posts %>
	</div>
</div>