config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :posts
  resources :reviews
  resources :registrations, only: [:create]
  root 'home#index'
  resources :tours do
    member do
      put 'like', to:'tours#upvote'
      put 'unlike', to:'tours#downvote'
    end
  end
  devise_for :users
  resources :joinedtours
  resources :wishlists
  resources :relationships, only: [:create, :destroy]
  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'logout', to: 'devise/sessions#destroy'
  get 'create', to: 'devise/registrations#new'
  resources :users, only: [:index, :show, :edit, :update, :change_name] do
    member do
      get 'following', to: 'users#following'
      get 'followers', to: 'users#followers'

    end
  end
end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
	belongs_to :host, class_name:"User", foreign_key:"host_id"
	has_many :reviews
	has_many_attached :images
	has_many :joinedtours
	has_many :wishlists
	has_many :interested_users, :through => :joinedtours, :source => :user
	has_many :wishlisted_by_users, :through => :wishlists, :source => :user
	acts_as_votable

	validates :title, presence: true, length: {maximum: 70}
	validates :description, presence: true, length: {maximum: 500}
	validates :budget, presence: true
	validates :reg_date_ends, presence: true
	validates :places, presence: true
	validates :services, presence: true
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.order(created: :desc).paginate(page: params[:page], per_page:10)
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    @reviews = @tour.reviews.order(created_at: :desc)
    @avg_rating = @tour.reviews.average(:rating)
    @review = Review.new
  end

  # GET /tours/new
  def new
    @tour = Tour.new
    @registration = Registration.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = current_user.hosted_tours.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @tour.upvote_by current_user
    redirect_to request.referrer
  end

  def downvote
    @tour.unliked_by current_user
    redirect_to request.referrer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:title, :description, :places, :services, :budget, :reg_date_ends, :pickup_spots, images: [])
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<div class="row">
  <div class=" col s12 col m6 center-align">
    <div class="row">
      <div class="col m6 offset-m3 s12">
<%= form_with(model: tour, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h5>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
</div>
  <div class="row">
  <div class="input-field col s6 offset-s1 offset-m5">
    <i class="material-icons prefix">local_offer</i>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  </div>
  <div class="row">
  <div class="input-field col s8 offset-s1 offset-m5">
    <i class="material-icons prefix">mode_edit</i>
    <%= form.label :description %>
    <%= form.text_area :description, class:"materialize-textarea" %>
  </div>
  </div>

  <div class="row">
  <div class="input-field col s6 offset-s1 offset-m5">
    <i class="material-icons prefix">room</i>
    <%= form.text_field :places %>
    <%= form.label :places, class:"" %>
  </div>

  <div class="input-field col s6 offset-s1 offset-m5">
    <i class="material-icons prefix">donut_small</i>
    <%= form.text_field :services, class:"" %>
     <%= form.label :services %>
  </div>
  </div>

  <div class="row">
  <div class="input-field col m4 col s8 offset-s1 offset-m5">
    <i class="material-icons prefix">monetization_on</i>
    <%= form.label :budget %>
    <%= form.text_field :budget %>
  </div>

  <div class="input-field col m4 col s8 offset-s1 offset-m5">
    <i class="material-icons prefix">date_ranger</i>
    <%= form.date_field :reg_date_ends %>
    <%= form.label :Deadline %>
  </div>

  <div class="input-field col m4 col s8 offset-s1 offset-m5">
    <i class="material-icons prefix">drive_eta</i>
    <%= form.label :pickup_spots %>
    <%= form.text_field :pickup_spots, class:"" %>
  </div>
  </div>


  <div class="row">
  <div class="input-field col m4 col s8 offset-s1 offset-m5">
   <div class="file-field input-field">
    <div class="btn ">
    <%= form.label :images, class:"black-text" %>
    <%= form.file_field :images, multiple: true %>
  </div>
  <div class="file-path-wrapper" >
    <%= form.text_field  class:"file-path validate", placeholder:"Upload one or more pictures" %>
  </div>
  </div>
  </div>
  </div>

  

  <div class="actions waves-effect waves-light btn offset-s3 offset-m6 ">
    <%= form.submit %>
  </div>   <div class="actions waves-effect waves-light btn offset-s3 offset-m6 ">
    <%= link_to "Home Page", root_path %>
  </div>
<% end %>
</div>
</div>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col s12 m7">
    <h2 class="header center-align">Tours</h2>
    <% @tours.each do |tour| %>
    <%= link_to  tour_path(tour) do %>
    <div class="card horizontal ">
    <% if tour.images.any? %>
      <div class="card-image hide-on-small-only">
        <%= image_tag tour.images[0], class:"img-wit" %>
      </div>
      <% end %>
      <div class="card-stacked center-align">
        <span class="card-title tito"><%= tour.title %></span> <span><i class="material-icons right share-btn">share</i></span>
        
        <div class="card-content">
          <p><%= tour.description %> </p>
          <div>
             <h5 class="left"><%= tour.budget %> Rs</h5>
             <h5 class="right"><%= tour.reg_date_ends %></h5>
          </div>
          <% end %>
        </div>

        <div class="card-action">

          <% if !current_user.wishlisted?(tour) %>

          <%= link_to wishlists_path(tour_id: tour.id), method: :post do %>
             <span class="badge"><i class="material-icons left marg">turned_in_not</i>14</span>
          <% end %>

          <% else %>
             <span class="badge"><i class="material-icons left marg">turned_in</i>14</span>
          <% end %>

          <span class="badge"><i class="material-icons left prefix marg">comment</i><%= tour.reviews.count %></span>

          <% if current_user.voted_for? tour %>

          <%= link_to unlike_tour_path(tour), method: :put, remote: true do %>

              <span class="badge"><i class="material-icons left ">favorite</i><%= tour.get_upvotes.size %></span>
          
          <% end %>

          <% else %>

          <%= link_to like_tour_path(tour), method: :put, remote: true do %>
              <span class="badge"><i class="material-icons left ">favorite_border</i><%= tour.get_upvotes.size %></span>
          <% end %>
            
          <% end %>
        </div>
        
      </div>
    </div>
    
  </div>
  <% end %>
<br>
<div class="center"><%= will_paginate @tours %></div>

app/views/tours/new.html.erb
<h3 class="center-align">New Tour</h3>
<% if current_user.paid? %>
<%= render 'form', tour: @tour, class:"right" %>
<% else %>
<div class="container">
	<div class="row">
		<div class="col m6 offset-m3 s12">
			<h2>Pay your one time dues to continue</h2>
			<%= form_for @registration do |form| %>
				<div class="field">
					<%= form.label :full_name %>
					<%= form.text_field :full_name %>
				</div>
				<div class="field">
					<%= form.label :email %>
					<%= form.email_field :email %>
				</div>
				<div class="field">
					<%= form.label :telephone %>
					<%= form.phone_field :telephone %>
				</div>
				<div class="actions">
					<Script class="stripe-button" src="https://checkout.stripe.com/checkout.js" data-amount="10000*100" data-description="One Time Payment" data-key= <%= Rails.application.secrets.stripe_publishable_key %> ></Script>
				</div>
			<% end %>
		</div>
	</div>
</div>
<% end %>
<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<div class="container">
  <div class="row initail-row">
    <div class="col s12" >
      <div class="row">
        <div class="col m5 s12" >
          <% if @tour.images.any? %>
          <%= image_tag @tour.images[0], class:"img-responsive img-wit" %>
          <% end %>
        </div>
        <div class="col m7 s12">
          <h4><%= @tour.title %></h4><span><i class="material-icons right share-btn">share</i></span>
          <h6><strong>Budget:</strong> <%= @tour.budget %> Rs</h6><span><i class="material-icons right share-btn">thumb_up</i></span>
          <div>
            <p>Deadline: <%= @tour.reg_date_ends %></p><br/><span><i class="material-icons right share-btn">comment</i></span>
          </div>

           <div>
            <p>Average Rating: <div class="review-rating" data-score="<%= @avg_rating %>" ></div>
          </div>

          <div>
            <% if current_user.joined?(@tour) %>
               <a class="waves-effect waves-light btn">joined</a>
               <% else %>
            <%= form_for(current_user.joinedtours.build) do |form| %>
                <div>
                  <%= hidden_field_tag(:tour_id, @tour.id) %>
                  <%= form.submit 'Join', class: "btn waves-effect waves-light" %>
                  </div>
                <% end %>
                <% end %>
            

                  <% if current_user.wishlisted?(@tour) %>
                  <div class="btn waves-effect waves-light">Added To Wishlist</div>

                  <% else %>
                  <div>
                  <%= form_for(current_user.wishlists.build) do |form| %>
                <div>
                  <%= hidden_field_tag(:tour_id, @tour.id) %>
                  <%= form.submit 'Add To Wishlist', class: "btn waves-effect waves-light" %>
                  </div>
                <% end %>
                  </div>
                  <% end %>



               </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <h5 class="left-align"> Description</h5>
          <p><%= @tour.description %></p>
        </div>
      </div>

      <h4 class="left-align" >Images of the places</h4>
          <% @tour.images.in_groups_of(3, false).each do |group| %>
          <div class="row">
            <% group.each do |image| %>
        <div class="col s12 m3 sty">
            <%= image_tag image, class:" img-wit materialboxed" %><span>  </span>
        </div>
        <% end %>
      </div>
      <% end %>

       <div class="row">
        <div class="col s12">
          <h5 class="left-align"> Places</h5>
          <p><%= @tour.places %></p>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <h5 class="left-align"> Services</h5>
          <p><%= @tour.services %></p>
        </div>
      </div>

      <div class="row">
        <div class="col s12">
          <h5 class="left-align"> Add Review</h5>
          <%= render 'reviews/form' %>
        </div>
      </div>

      <div class="row">
        <div class="col s12">
          <h5 class="left-align"> Reviews</h5>
          <% @reviews.each do |review| %>
          <div class="review-rating" data-score="<%= review.rating %>" ></div>
          "<%= review.comment %>" 
          <br/>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>


<script type="text/javascript">
  $('.review-rating').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>