config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :posts
  resources :reviews
  resources :registrations, only: [:create]
  root 'home#index'
  resources :tours do
    member do
      put 'like', to:'tours#upvote'
      put 'unlike', to:'tours#downvote'
    end
  end
  devise_for :users
  resources :joinedtours
  resources :wishlists
  resources :relationships, only: [:create, :destroy]
  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'logout', to: 'devise/sessions#destroy'
  get 'create', to: 'devise/registrations#new'
  resources :users, only: [:index, :show, :edit, :update, :change_name] do
    member do
      get 'following', to: 'users#following'
      get 'followers', to: 'users#followers'

    end
  end
end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/joinedtour.rb
class Joinedtour < ApplicationRecord
	belongs_to :tour
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many_attached :images
  validates :content, presence: true
  validates :user_id, presence: true

end

app/models/registration.rb
class Registration < ApplicationRecord
	belongs_to :user

	def process_payments
		customer = Stripe::Customer.create(email: email, card: card_token)
		Stripe::Charge.create(customer: customer.id,
			                   amount: 10000*100,
			                   description: 'One Time Payment',
			                   currency: 'usd')
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name:"User", foreign_key:"follower_id"
	belongs_to :followed, class_name:"User", foreign_key:"followed_id"
end

app/models/response.rb
class Response < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :tour
	belongs_to :user
end

app/models/tour.rb
class Tour < ApplicationRecord
	belongs_to :host, class_name:"User", foreign_key:"host_id"
	has_many :reviews
	has_many_attached :images
	has_many :joinedtours
	has_many :wishlists
	has_many :interested_users, :through => :joinedtours, :source => :user
	has_many :wishlisted_by_users, :through => :wishlists, :source => :user
	acts_as_votable

	validates :title, presence: true, length: {maximum: 70}
	validates :description, presence: true, length: {maximum: 500}
	validates :budget, presence: true
	validates :reg_date_ends, presence: true
	validates :places, presence: true
	validates :services, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         acts_as_voter 
         
         has_many :hosted_tours, class_name:"Tour", foreign_key:"host_id"
         has_many :reviews
         has_many :blogs
         has_many :posts
         has_many :comments
         has_many :joinedtours
         has_many :wishlists
         has_many :interested_tours, :through => :joinedtours, :source => :tour
         has_many :wishlisted_tours, :through => :wishlists, :source => :tour
         has_one_attached :profile
         has_one :registration

         ## relationship section

         has_many :active_relationships, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
         has_many :passive_relationships, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy

         has_many :followers, through: :passive_relationships, source: :follower
         has_many :following, through: :active_relationships, source: :followed

         ###
         before_save :email_down
         VALID_REGEX_VALUE = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :first_name, presence: true, length: { maximum: 50 }
    validates :profile, presence: true
    validates :last_name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
         format: { with: VALID_REGEX_VALUE }, uniqueness: { case_sensitive: false }

         ### tour section
         def join tour
         	interested_tours << tour
         	if wishlisted?(tour)
         		remove_from_wishlist(tour)
         	end
         end
         def feed
            following_ids_subselect = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
            Post.where(" user_id IN (#{following_ids_subselect}) OR user_id = :user_id", user_id: id)
        end

         def joined?(tour)
         	interested_tours.include?(tour)
         end


         #### wishlist section
         def add_to_wishlist tour
         	wishlisted_tours << tour
         end

         def wishlisted?(tour)
         	wishlisted_tours.include?(tour)
         end

         def remove_from_wishlist(tour)
         	wishlisted_tours.delete(tour)
         end

         #### relationship section

         def follow(user)
             following << user
         end

         def unfollow(user)
             following.delete(user)
         end

         def followed?(user)
             following.include?(user)
         end

private

def email_down
    self.email = email.downcase
end



end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :tour
	belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize: local_assigns[:in_gallery] ? "200x200" : "600x600") %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TourTogether</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      

  </head>

  <body>


<div class="navbar-fixed">
    <nav class="teal">
      <div class="container">
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">Tour <span class="hide-on-small-only">Together</span></a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
           <ul class="right hide-on-med-and-down desktop-menu">
            <% if user_signed_in? %>
            <li>
              <%= link_to 'Home', root_path %>
            </li>
            <li>
              <%= link_to 'Tours', tours_path, class:' waves-effect waves-light' %>
            </li>
            
            <li>
              <%= link_to 'Users', users_path %>
            </li>
            <li>
              <%= link_to 'Wishlist',  wishlists_path %>

            </li>
            <li>
              <!-- Dropdown Trigger -->
               <a class='dropdown-trigger' href='#' data-target='dropdown1'><%= current_user.first_name.capitalize %><i class="material-icons right">arrow_drop_down</i></a>

  <!-- Dropdown Structure -->
            <ul id='dropdown1' class='dropdown-content d-down'>
                  <li><%= link_to current_user.first_name, user_path(current_user) %></li>
                  <li><%= link_to 'Creat tour', new_tour_path %></li>
                  <li class="divider" tabindex="-1"></li>
                  <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
                  <li><%=link_to 'Log out', logout_path %></li>
            </ul>
            </li>
            

              

            <% else %>
             <li>
             </span><%= link_to 'Sign In', login_path %>
            </li> 
            <li>
              <%= link_to 'Sign up', create_path %>            
             </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <ul class="sidenav" id="mobile-demo">
    <% if user_signed_in? %>
    <li>
      <%= link_to current_user.first_name, user_path(current_user) %>
    </li>
    <div class="divider" ></div>
    <li>
      <%= link_to 'Tours', tours_path %>
    </li>
    
    <li>
      <%= link_to 'Wislist', wishlists_path %>
      
    </li>
    <li>
      <%= link_to 'Users', users_path %>
      
    </li>
    <div class="divider" ></div>
     <li>
      <%= link_to 'Create Tour', new_tour_path %>
      
    </li> 
     <li>
      <%= link_to 'Logout', logout_path %>
      
    </li>
    <% else %>
    <li>
      <%= link_to 'Sign in', login_path %>
    </li><li>
      <%= link_to 'Sign up', create_path %>
    </li>
    <% end %>

  </ul>

    <%= yield %>
        <div style="bottom:0;">
        <footer class="page-footer teal">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Tour Together</h5>
                <p class="grey-text text-lighten-4">A platform where you get connected with other fellows of same interests</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><%= link_to 'Create Tour', new_tour_path %></li>
                  <li><%= link_to 'Join Tour', tours_path %></li>
                  <li><%= link_to 'Write Post', root_path %></li>
                  <li><%= link_to 'Update Ino', edit_user_path(current_user) %></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container center">
            © Project By Ameer Hamza
            </div>
          </div>
        </footer>
      </div>
      

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>